### PR TITLE
Fix: fix spawn on Windows

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks! Could you explain what the issue this PR is trying to fix?

**Comment by targos** [comment]
Sure. On Windows, executable files usually have extensions (`.exe` or `.cmd`). It is possible to run them without providing the extension only in the context of a shell.
In Node.js, `spawn` and `execFile` calls do not run the command in a shell by default, so it fails to find the executable:

```
> child_process.execFileSync('npm', ['--version']).toString()
Thrown:
Error: spawnSync npm ENOENT
```

There are two possible solutions:

Explicitly add the extension:
```
> child_process.execFileSync('npm.cmd', ['--version']).toString()
'6.10.3\n'
```

Run the command with `shell: true`:
```
> child_process.execFileSync('npm', ['--version'], { shell: true }).toString()
'6.10.3\n'
```

I chose the first one.

**Comment by sapegin** [comment]
Make sense, thanks!

Why did you choose the first approach over the second one that wouldn't require a condition and hardcoding two executable names? What would be the downsides of the second one?

**Comment by targos** [comment]
It should be avoided if possible to run in a shell because the behavior can be different depending the environment of the user. I also expect it to be faster and safer.

**Comment by sapegin** [comment]
The I'd isolate this at least at the beginning of a file, ideally in a separate modules with comments and tests. Littering code with `isWindows` checks isn't great.

**Comment by targos** [comment]
How do you suggest to isolate this?

**Comment by sapegin** [comment]
Something like 

```js
const execCommand = (command, ...args) =>
  exec(os.platform() === 'win32' ? `${command}.cmd` : command, ...args);
```

It's not perfect but at least the platform check is in one place.

**Comment by targos** [comment]
Done

**Comment by sapegin** [comment]
Thanks, merging! 🐚

**Pull request merged**
