### PR TITLE
Resolve "Make prettify of ini configurable"

### LINKED ISSUE #10: Make prettify of ini configurable
I was curious if there is a chance of making the prettify step within the save function of ini files configurable? 

This is how I would imagine the api.
```
ini('file.ini').save({ prettify: false });
```

I would be willing to implement, just asking ahead not to waste time.

PS. Thanks so much for this awesome project :)

### PR DESCRIPTION
**Pull request by noxan**
Closes #10.

Some stylistic questions:
1) I was wondering if the current api is good, or using `ini.save({ withSpaces: false });` would be better.

2) Is `withSpaces` a good name? Or would the inverted logic be better? Using `removeSpaces` or `withoutSpaces` instead and also changing default parameter values.

I would implement auto detection afterwards in order not to refactor too much. Could also do it as a follow up issue, let me know what you think is best 👍 
  
EDIT: Just found my own original api proposal, using `{ prettify: false }` but not so happy unless we change logic to really NOT prettify at all, which I dislike over either having spaces or not.

### CODE REVIEW

**Review by sapegin — CHANGES_REQUESTED** [review]
Thanks!

> I was wondering if the current api is good, or using ini.save({ withSpaces: false }); would be better.

I think this is the best API. Boolean arguments aren't very clear.

> I would implement auto detection afterwards in order not to refactor too much. Could also do it as a follow up issue, let me know what you think is best 👍

Up to you, both are fine for me.

**Comment by noxan** [comment]
I still need to find a good regex or logic to ignore comments within the detection of spaces. Everything else should be working.

**Comment by sapegin** [comment]
Maybe it would be better to test for a property name + `=` instead of just a `=` anywhere.

**Comment by noxan** [comment]
https://regex101.com/r/fppjPM/1

**Comment by sapegin** [comment]
I think this should be enough: `/^\w+\s*=\s*/gm`.

**Comment by sapegin** [comment]
Thanks, merged!

**Pull request merged**
